/*-------------------------------------------------------------------------
Compiler Generator Coco/R,
Copyright (c) 1990, 2004 Hanspeter Moessenboeck, University of Linz
extended by M. Loeberbauer & A. Woess, Univ. of Linz
ported to C++ by Csaba Balazs, University of Szeged
with improvements by Pat Terry, Rhodes University

This program is free software; you can redistribute it and/or modify it 
under the terms of the GNU General Public License as published by the 
Free Software Foundation; either version 2, or (at your option) any 
later version.

This program is distributed in the hope that it will be useful, but 
WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY 
or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License 
for more details.

You should have received a copy of the GNU General Public License along 
with this program; if not, write to the Free Software Foundation, Inc., 
59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.

As an exception, it is allowed to write an extension of Coco/R that is
used as a plugin in non-free software.

If not otherwise stated, any source code generated by Coco/R (other than 
Coco/R itself) does not fall under the GNU General Public License.
-------------------------------------------------------------------------*/

#include <string.h>
#include "StringBuilder.h"

namespace Coco {

void StringBuilder::Init(int capacity) {
	length = 0;
	this->_capacity = capacity;
	data = new wchar_t[capacity + 1];
	data[0] = 0;	
}

StringBuilder::StringBuilder(int capacity) {
	Init(capacity);
}

StringBuilder::StringBuilder(const wchar_t *val) {
	Init(wcslen(val));
	wcscpy(data, val);
}

StringBuilder::~StringBuilder() {
	if (data != NULL) {
		delete [] data;
		data = NULL;
		length = 0;
		_capacity = 0;
	}
}

void StringBuilder::capacity(int new_capacity) {
        wchar_t *nData = new wchar_t[new_capacity + 1];
        memcpy(nData, data, _capacity * sizeof(wchar_t));
        delete [] data;
        data = nData;
        _capacity = new_capacity;
}

void StringBuilder::Append(const int value) {
	if (length == _capacity) {
                capacity(_capacity * 2);
	}
	
	data[length] = value;
	length++;
	data[length] = _SC('\0');
}

void StringBuilder::Append(const wchar_t *value) {
	int slen = (int)wcslen(value);
	if (length + slen >= _capacity) {
            capacity(length + slen + 1);
        }
        wcscpy(data + length, value);
        length += slen;
}


wchar_t* StringBuilder::ToString() {
	return coco_string_create(data);
}

}; // namespace
