/*-------------------------------------------------------------------------
Tab -- Symbol Table Management
Compiler Generator Coco/R,
Copyright (c) 1990, 2004 Hanspeter Moessenboeck, University of Linz
extended by M. Loeberbauer & A. Woess, Univ. of Linz
ported to C++ by Csaba Balazs, University of Szeged
with improvements by Pat Terry, Rhodes University

This program is free software; you can redistribute it and/or modify it
under the terms of the GNU General Public License as published by the
Free Software Foundation; either version 2, or (at your option) any
later version.

This program is distributed in the hope that it will be useful, but
WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
for more details.

You should have received a copy of the GNU General Public License along
with this program; if not, write to the Free Software Foundation, Inc.,
59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.

As an exception, it is allowed to write an extension of Coco/R that is
used as a plugin in non-free software.

If not otherwise stated, any source code generated by Coco/R (other than
Coco/R itself) does not fall under the GNU General Public License.
-------------------------------------------------------------------------*/

#if !defined(COCO_TAB_H__)
#define COCO_TAB_H__

#include "Scanner.h"
#include "HashTable.h"
#include "StringBuilder.h"
#include "SortedList.h"
#include "Position.h"
#include "Symbol.h"
#include "Node.h"
#include "Graph.h"
#include "Sets.h"
#include "CharClass.h"

namespace Coco {

class Errors;
class Parser;
class BitArray;

class Tab {
public:
	Position *semDeclPos;       // position of global semantic declarations
	CharSet *ignored;           // characters ignored by the scanner
	bool ddt[10];                  // debug and test switches
	Symbol *gramSy;             // root nonterminal; filled by ATG
	Symbol *eofSy;              // end of file symbol
	Symbol *noSym;              // used in case of an error
	BitArray *allSyncSets;      // union of all synchronisation sets
	HashTable literals;        // symbols that are used as literals

	wchar_t* srcName;            // name of the atg file (including path)
	wchar_t* srcDir;             // directory path of the atg file
	wchar_t* nsName;             // namespace for generated files
	wchar_t* frameDir;           // directory containing the frame files
	wchar_t* outDir;             // directory for generated files
	bool checkEOF;               // should coco generate a check for EOF at
	                             // the end of Parser.Parse():
	bool emitLines;              // emit line directives in generated parser

	BitArray *visited;                // mark list for graph traversals
	Symbol *curSy;                     // current symbol in computation of sets

	Parser *parser;                    // other Coco objects
	FILE* trace;

	Errors *errors;

	TArrayList<Symbol*> terminals;
	TArrayList<Symbol*> pragmas;
	TArrayList<Symbol*> nonterminals;


	TArrayList<Node*> nodes;
	static const char* nTyp[];
	Node *dummyNode;

	TArrayList<CharClass*> classes;
	int dummyName;

	Tab(Parser *parser);
        ~Tab();

	//---------------------------------------------------------------------
	//  Symbol list management
	//---------------------------------------------------------------------


	static const char* tKind[];

	Symbol* NewSym(int typ, const wchar_t* name, int line, int col);
	Symbol* FindSym(const wchar_t* name);
	int Num(const Node *p);
	void PrintSym(const Symbol *sym);
	void PrintSymbolTable();
	void PrintSet(const BitArray *s, int indent);

	//---------------------------------------------------------------------
	//  Syntax graph management
	//---------------------------------------------------------------------

	Node* NewNode(int typ, Symbol *sym, int line, int col);
	Node* NewNode(int typ, Node* sub);
	Node* NewNode(int typ, int val, int line, int col);
	void MakeFirstAlt(Graph *g);
	void MakeAlternative(Graph *g1, Graph *g2);
	void MakeSequence(Graph *g1, Graph *g2);
	void MakeIteration(Graph *g);
	void MakeOption(Graph *g);
	void Finish(Graph *g); //set all 'next' from g->r to NULL
	void DeleteNodes();
	Graph* StrToGraph(const wchar_t* str);
	void SetContextTrans(Node *p); // set transition code in the graph rooted at p

	//------------ graph deletability check -----------------

	bool DelGraph(const Node* p);
	bool DelSubGraph(const Node* p);
	bool DelNode(const Node* p);

	//----------------- graph printing ----------------------

	int Ptr(const Node *p, bool up);
	void PrintNodes();

	//---------------------------------------------------------------------
	//  Character class management
	//---------------------------------------------------------------------

	CharClass* NewCharClass(const wchar_t* name, CharSet *s);
	CharClass* FindCharClass(const wchar_t* name);
	CharClass* FindCharClass(const CharSet *s);
	CharSet* CharClassSet(int i);

	//----------- character class printing

	void WriteCharSet(const CharSet *s);
	void WriteCharClasses ();

	//---------------------------------------------------------------------
	//  Symbol set computations
	//---------------------------------------------------------------------

	/* Computes the first set for the given Node. */
	BitArray* First0(const Node *p, BitArray *mark);
	BitArray* First(const Node *p);
	void CompFirstSets();
	void CompFollow(Node *p);
	void Complete(Symbol *sym);
	void CompFollowSets();
	const Node* LeadingAny(const Node *p);
	void FindAS(const Node *p); // find ANY sets
	void CompAnySets();
	BitArray* Expected(const Node *p, const Symbol *curSy);
	// does not look behind resolvers; only called during LL(1) test and in CheckRes
	BitArray* Expected0(const Node *p, const Symbol *curSy);
	void CompSync(Node *p);
	void CompSyncSets();
	void SetupAnys();
	void CompDeletableSymbols();
	void RenumberPragmas();
	void CompSymbolSets();

	//---------------------------------------------------------------------
	//  String handling
	//---------------------------------------------------------------------

	wchar_t  Hex2Char(const wchar_t* s, int len);
	wchar_t* Unescape(const wchar_t* s);
	wchar_t* Escape(const wchar_t* s);

	//---------------------------------------------------------------------
	//  Grammar checks
	//---------------------------------------------------------------------

	bool GrammarOk();
        bool GrammarCheckAll();

	//--------------- check for circular productions ----------------------

	class CNode {	// node of list for finding circular productions
	public:
		const Symbol *left, *right;

		CNode (const Symbol *l, const Symbol *r) {
			left = l; right = r;
		}
	};

	void GetSingles(const Node *p, TArrayList<Symbol*> &singles, const Node *rule);
	bool NoCircularProductions();

	//--------------- check for LL(1) errors ----------------------

	void LL1Error(int cond, const Symbol *sym);
	int CheckOverlap(const BitArray *s1, const BitArray *s2, int cond);
	void PrintFirstPath(const Node *p, int tok, const wchar_t *indent=_SC("\t"));
	int CheckAlts(Node *p);
	void CheckLL1();

	//------------- check if resolvers are legal  --------------------

	void ResErr(const Node *p, const wchar_t* msg);
	void CheckRes(const Node *p, bool rslvAllowed);
	void CheckResolvers();

	//------------- check if every nts has a production --------------------

	bool NtsComplete();

	//-------------- check if every nts can be reached  -----------------

	void MarkReachedNts(const Node *p);
	bool AllNtReached();

	//--------- check if every nts can be derived to terminals  ------------

	bool IsTerm(const Node *p, const BitArray *mark); // true if graph can be derived to terminals
	bool AllNtToTerm();

	//---------------------------------------------------------------------
	//  Cross reference list
	//---------------------------------------------------------------------

	void XRef();
	void SetDDT(const wchar_t* s);
	void SetOption(const wchar_t* s);

};

}; // namespace

#endif // !defined(COCO_TAB_H__)
